"""
Django settings for AgileLink project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = ""

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'Agile_models',  # 处理数据库
    'corsheaders',  # 跨域请求
    'Team_manage',  # 处理团队管理
    'Public_chat',  # 处理公共聊天
    'Notice_center',  # 处理通知中心
    'Project_manage',  # 处理项目管理
    'Prototype_design',  # 处理原型设计
    'Doc_edit',  # 处理文档编辑
    'channels',  # 处理websocket
    'AgileLink'
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # 跨域请求
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "AgileLink.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
CORS_ORIGIN_ALLOW_ALL = True
WSGI_APPLICATION = "AgileLink.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# MySQL数据库配置
mysql_ENGINE = 'django.db.backends.mysql'  # 这个不需要修改
mysql_NAME = ''  # 这个自己创建的数据库的名称
mysql_USER = ''  # 数据库的账户，如果是本地的数据库一般为 root
mysql_PASSWORD = ''  # 数据库账户对应的密码
mysql_HOST = ''  # 一般购买的云数据库对应路由和这个很类似，这是阿里云数据库的路由，
# 如果是本地的mysql一般默认为 127.0.0.1
# 如果是自己的服务器安装的mysql一般默认为服务器的公网IP
mysql_PORT = ''  # 这个除非自己特别设置过，否则本地mysql和购买的云数据库端口都是默认3306，当然如果是自己在服务器上安装的mysql可以修改端口，
# 但是务必保证该端口对应的防火墙是打开的

DATABASES = {
    'default': {
        'ENGINE': mysql_ENGINE,
        'NAME': mysql_NAME,
        'USER': mysql_USER,
        'PASSWORD': mysql_PASSWORD,
        'HOST': mysql_HOST,
        'PORT': mysql_PORT,
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "zh-hans"

TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
ASGI_APPLICATION = 'AgileLink.asgi.application'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}
BACKEND_URL = ""
WKHTMLTOPDF_PATH = r'/usr/bin/wkhtmltopdf'
